datasource:
  db:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080

security:
  accessTokenExpirationInMs: 86400000 # 1 day
  refreshTokenExpirationInMs: 7776000000 # 90 days
  secret-key: FB3B63E6E94DFA04C3C10E2E2C2CCC001EF83C13F504F76A93CA874B701415E1

  spring:
    jpa:
      show-sql: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true

  logging:
    level:
      org:
        springframework:
          jdbc:
            core:
              JdbcTemplate: DEBUG
              StatementCreatorUtils: TRACE
        hibernate:
          type:
            descriptor:
              sql: trace